# Generated by Django 3.2 on 2021-04-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("crypto", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Screener",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Indicator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("MM7", "Moyenne mobile 7"),
                            ("MM20", "Moyenne mobile 20"),
                            ("MM50", "Moyenne mobile 50"),
                            ("MM100", "Moyenne mobile 100"),
                            ("MM200", "Moyenne mobile 200"),
                            ("price", "Price"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                ("value", models.FloatField(null=True)),
                (
                    "quote",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicators",
                        to="crypto.quote",
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("MM7", "Moyenne mobile 7"),
                            ("MM20", "Moyenne mobile 20"),
                            ("MM50", "Moyenne mobile 50"),
                            ("MM100", "Moyenne mobile 100"),
                            ("MM200", "Moyenne mobile 200"),
                            ("price", "Price"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            (">", "GREATER THAN"),
                            ("<", "GREATER THAN"),
                            ("<=", "LOWER OR EQUAL"),
                            ("==", "EQUAL"),
                            (">=", "GREATER OR EQUAL"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "other_name",
                    models.CharField(
                        choices=[
                            ("MM7", "Moyenne mobile 7"),
                            ("MM20", "Moyenne mobile 20"),
                            ("MM50", "Moyenne mobile 50"),
                            ("MM100", "Moyenne mobile 100"),
                            ("MM200", "Moyenne mobile 200"),
                            ("price", "Price"),
                        ],
                        max_length=128,
                    ),
                ),
                ("day_number", models.IntegerField(default=1)),
                (
                    "condition",
                    models.CharField(
                        choices=[("AND", "AND"), ("OR", "OR"), ("DISABLED", "None")],
                        max_length=16,
                    ),
                ),
                (
                    "screener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditions",
                        to="decision_maker.screener",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="indicator",
            constraint=models.UniqueConstraint(
                fields=("name", "quote"), name="unique_per_name_and_quote"
            ),
        ),
    ]
