# Generated by Django 3.2 on 2021-05-02 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crypto", "0002_alter_quote_time_unit"),
        ("decision_maker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SymbolIndicator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, null=True)),
                ("value", models.FloatField(null=True)),
                (
                    "symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicators",
                        to="crypto.symbol",
                    ),
                ),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.AddConstraint(
            model_name="symbolindicator",
            constraint=models.UniqueConstraint(
                fields=("name", "symbol"), name="unique_per_name_and_symbol"
            ),
        ),
    ]
